### ISSUE TITLE
Uncaught TypeError: this._parseListTags is not a function

### ISSUE THREAD

**Issue by keirlawson** [steveukx/git-js#59]
When trying to use tag with 1.15, worked with 1.14
